CREATE TABLE Felhasznalo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nev TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  jelszoHash TEXT NOT NULL,
  szerepkor TEXT NOT NULL DEFAULT 'FELHASZNALO',
  letrehozva DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Film (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cim TEXT NOT NULL,
  leiras TEXT NOT NULL,
  hosszPerc INTEGER NOT NULL,
  kepUrl TEXT,
  letrehozva DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Vetites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filmId INTEGER NOT NULL,
  kezdesIdopont DATETIME NOT NULL,
  terem TEXT NOT NULL,
  osszesHely INTEGER NOT NULL,
  letrehozva DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (filmId) REFERENCES Film(id)
);

CREATE TABLE Foglalas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  felhasznaloId INTEGER NOT NULL,
  vetitesId INTEGER NOT NULL,
  helyekSzama INTEGER NOT NULL,
  letrehozva DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (felhasznaloId) REFERENCES Felhasznalo(id),
  FOREIGN KEY (vetitesId) REFERENCES Vetites(id)
);